# -*- coding: utf-8 -*-
"""Hybrid_Final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xTuaN40mFGQVrfGb_y-lXX--qjt4rqTC
"""

# -*- coding: utf-8 -*-
"""
================================================================================
HYBRID MOVIE RECOMMENDATION SYSTEM — WITH PROPER COLD-START HANDLING
================================================================================
Dataset: Kaggle's "The Movies Dataset"
Files Required in the working directory:
    movies_metadata.csv, credits.csv, keywords.csv,
    ratings_small.csv, links_small.csv

Design summary
---------------
1. Content-based engine: TF-IDF over overview + genres + keywords + cast + director.
2. Collaborative engine: user-user cosine similarity (KNN), fit once and reused.
3. Hybrid engine with three cold-start regimes, each handled explicitly:
     a. No usable movie AND no known user  -> popularity fallback
        (IMDB-style Bayesian weighted rating, not just "first N rows").
     b. Known movie but unknown/new user   -> alpha = 0 (100% content-based).
     c. Known user                         -> alpha rises smoothly with the
        user's rating count (graduated confidence), instead of jumping from
        0 straight to a fixed 0.5 the moment the user has a single rating.
   Item-level cold start is also handled: if a specific candidate movie has
   no collaborative signal (nobody rated it, or it's outside the small-ratings
   sample), that movie's item-level alpha drops to 0 and it is scored purely
   on content — even for an otherwise "warm" user.
4. Content ids and collaborative ids live in different spaces (TMDB id vs.
   MovieLens movieId). links_small.csv is used to bridge collaborative
   output back into TMDB id space *before* merging, so the hybrid blend
   is comparing the same movies rather than two disjoint candidate sets.
================================================================================
"""

import ast
import difflib
import numpy as np
import pandas as pd
from nltk.stem.porter import PorterStemmer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.neighbors import NearestNeighbors


# -----------------------------------------------------------------------------
# 1. DATA PARSING HELPERS
# -----------------------------------------------------------------------------
def genre_extract(col):
    try:
        return [i['name'] for i in ast.literal_eval(col)]
    except Exception:
        return []


def keyword_extract(col):
    try:
        return [i['name'] for i in ast.literal_eval(col)]
    except Exception:
        return []


def cast_extract(col):
    try:
        L = []
        for j, i in enumerate(ast.literal_eval(col)):
            if j >= 3:
                break
            L.append(i['name'])
        return L
    except Exception:
        return []


def crew_extract(col):
    try:
        for i in ast.literal_eval(col):
            if i.get('job') == 'Director':
                return [i['name']]
    except Exception:
        pass
    return []


# -----------------------------------------------------------------------------
# 2. BUILD CONTENT-BASED FEATURE SPACE (keyed by TMDB id, not by title string)
# -----------------------------------------------------------------------------
def build_content_based():
    movies = pd.read_csv('movies_metadata.csv', low_memory=False)
    credits = pd.read_csv('credits.csv')
    keywords = pd.read_csv('keywords.csv')

    movies = movies[movies['id'].apply(lambda x: str(x).isdigit())].copy()
    movies['id'] = movies['id'].astype(int)
    # Dedup by unique id, NOT by title — remakes/reused titles would otherwise collide
    movies = movies.drop_duplicates(subset='id')

    credits['id'] = credits['id'].astype(int)
    keywords['id'] = keywords['id'].astype(int)

    data = movies.merge(credits, on='id').merge(keywords, on='id')
    data = data[['genres', 'id', 'keywords', 'overview', 'title', 'cast', 'crew']]
    data.dropna(subset=['id', 'title'], inplace=True)
    data.reset_index(drop=True, inplace=True)

    data['genres'] = data['genres'].apply(genre_extract)
    data['keywords'] = data['keywords'].apply(keyword_extract)
    data['cast'] = data['cast'].apply(cast_extract)
    data['crew'] = data['crew'].apply(crew_extract)
    data['overview'] = data['overview'].fillna('').apply(lambda x: str(x).split())

    data['cast'] = data['cast'].apply(lambda x: [i.replace(" ", "") for i in x])
    data['crew'] = data['crew'].apply(lambda x: [i.replace(" ", "") for i in x])
    data['genres'] = data['genres'].apply(lambda x: [i.replace(" ", "") for i in x])
    data['keywords'] = data['keywords'].apply(lambda x: [i.replace(" ", "") for i in x])

    data['tags'] = data['overview'] + data['genres'] + data['keywords'] + data['cast'] + data['crew']
    data['clean_tags'] = data['tags'].apply(lambda x: " ".join(x).lower())
    data['title'] = data['title'].apply(lambda x: str(x).lower())

    ps = PorterStemmer()

    def stemming(text):
        return " ".join(ps.stem(word) for word in text.split())

    data['clean_tags'] = data['clean_tags'].apply(stemming)

    tfidf = TfidfVectorizer(max_features=5000, stop_words='english')
    vectors = tfidf.fit_transform(data['clean_tags']).toarray()

    all_titles = data['title'].tolist()
    title_to_pos = {t: i for i, t in enumerate(data['title'])}
    pos_to_id = data['id'].to_dict()
    id_to_title = data.set_index('id')['title'].to_dict()

    return data, vectors, all_titles, title_to_pos, pos_to_id, id_to_title


# -----------------------------------------------------------------------------
# 3. POPULARITY FALLBACK (for true cold start — no user, no seed movie)
# -----------------------------------------------------------------------------
def build_popularity_table():
    """IMDB-style Bayesian weighted rating: WR = (v/(v+m))*R + (m/(v+m))*C"""
    pop = pd.read_csv('movies_metadata.csv', low_memory=False)[['id', 'vote_average', 'vote_count']]
    pop = pop[pop['id'].apply(lambda x: str(x).isdigit())].copy()
    pop['id'] = pop['id'].astype(int)
    pop = pop.drop_duplicates(subset='id')
    pop['vote_average'] = pd.to_numeric(pop['vote_average'], errors='coerce').fillna(0)
    pop['vote_count'] = pd.to_numeric(pop['vote_count'], errors='coerce').fillna(0)

    C = pop['vote_average'].mean()
    m = pop['vote_count'].quantile(0.90)

    pop['weighted_rating'] = (
        pop['vote_count'] / (pop['vote_count'] + m) * pop['vote_average']
        + m / (pop['vote_count'] + m) * C
    )
    return pop.sort_values('weighted_rating', ascending=False).reset_index(drop=True)


# -----------------------------------------------------------------------------
# 4. CONTENT-BASED RECOMMENDER
# -----------------------------------------------------------------------------
def find_closest_titles(query, all_titles, n=5, cutoff=0.5):
    query = query.lower().strip()
    close = difflib.get_close_matches(query, all_titles, n=n, cutoff=cutoff)
    if close:
        return close
    return [t for t in all_titles if query in t][:n]


def recommend_content(movie_title, vectors, all_titles, title_to_pos, pos_to_id, top_n=10):
    """Returns (seed_tmdb_id, [(tmdb_id, similarity), ...]) or (None, []) if not found."""
    q = movie_title.lower().strip()
    if q not in title_to_pos:
        suggestions = find_closest_titles(q, all_titles)
        if suggestions:
            print(f"'{q}' not found in dataset. Did you mean one of these?")
            for s in suggestions:
                print(" -", s)
        else:
            print(f"'{q}' not found in dataset.")
        return None, []

    idx = title_to_pos[q]
    seed_id = pos_to_id[idx]
    sims = cosine_similarity(vectors[idx].reshape(1, -1), vectors).flatten()
    top_idx = sims.argsort()[::-1][1:top_n + 1]
    return seed_id, [(pos_to_id[i], float(sims[i])) for i in top_idx]


# -----------------------------------------------------------------------------
# 5. COLLABORATIVE FILTERING ENGINE
# -----------------------------------------------------------------------------
def build_collaborative(data):
    ratings = pd.read_csv('ratings_small.csv')
    links = pd.read_csv('links_small.csv')

    links = links.dropna(subset=['tmdbId']).copy()
    links['tmdbId'] = links['tmdbId'].astype(int)

    movie_map = links.merge(data[['id']], left_on='tmdbId', right_on='id', how='inner')
    movie_map = movie_map.drop_duplicates(subset='movieId')
    # Bridge: MovieLens movieId -> TMDB id, so collaborative output can be
    # merged with content output later in a shared id space.
    movieid_to_tmdbid = movie_map.set_index('movieId')['id'].to_dict()

    ratings = ratings.merge(movie_map[['movieId']], on='movieId', how='inner')

    user_pivot = ratings.pivot_table(index='userId', columns='movieId', values='rating').fillna(0)
    user_rating_matrix = user_pivot.values
    movie_columns = user_pivot.columns.to_numpy()
    user_index = {uid: pos for pos, uid in enumerate(user_pivot.index)}

    # Fit once here; reused on every call instead of refitting per-recommendation.
    nbrs = NearestNeighbors(metric='cosine', algorithm='brute')
    if len(user_rating_matrix) > 0:
        nbrs.fit(user_rating_matrix)

    nonzero = user_pivot.where(user_pivot > 0)
    user_rating_counts = nonzero.count(axis=1).to_dict()
    user_means = nonzero.mean(axis=1).to_dict()
    user_stds = nonzero.std(axis=1).fillna(0).to_dict()

    return (user_rating_matrix, movie_columns, user_index, movieid_to_tmdbid,
            nbrs, user_rating_counts, user_means, user_stds)


def recommend_user_based(target_user, user_rating_matrix, movie_columns, user_index,
                          movieid_to_tmdbid, nbrs, user_means=None, top_n=10, k=10,
                          shrinkage_k=2.0):
    """Returns [(tmdb_id, predicted_rating), ...]. Empty list if user is unknown
    or no confident predictions can be made — no exceptions, clean status only.

    A raw prediction backed by only 1-2 neighbors is statistically weak, but
    a similarity-weighted average collapses to exactly that neighbor's rating
    when they're the only one who rated the movie — so a single 5-star vote
    was hitting the ceiling and outranking predictions built from many
    neighbors. Fix: shrink low-support predictions toward the target user's
    own mean rating, in proportion to how many neighbors actually voted
    (support_count). shrinkage_k controls how aggressively: with the default
    of 2.0, a 1-neighbor prediction is pulled about 2/3 of the way back to
    the user's mean, while a 10-neighbor prediction is barely shrunk at all.
    """
    if target_user not in user_index:
        return []

    idx = user_index[target_user]
    n_neighbors = min(k + 1, len(user_rating_matrix))
    distances, indices = nbrs.kneighbors([user_rating_matrix[idx]], n_neighbors=n_neighbors)
    distances, indices = distances.flatten(), indices.flatten()
    sims = 1 - distances

    # Remove the user's own row by matching its actual index, not by
    # assuming it's always in position 0 (safe even with tied/duplicate rows).
    mask = indices != idx
    indices, sims = indices[mask], sims[mask]
    if len(indices) == 0:
        return []

    top_k_ratings = user_rating_matrix[indices]
    weighted_sum = sims @ top_k_ratings
    rated_mask = (top_k_ratings > 0).astype(float)
    weight_totals = sims @ rated_mask
    support_count = rated_mask.sum(axis=0)  # how many neighbors actually rated each movie

    with np.errstate(divide='ignore', invalid='ignore'):
        raw_predicted = np.where(weight_totals > 0, weighted_sum / weight_totals, 0.0)

    user_fallback = user_means.get(target_user, 3.5) if user_means else 3.5
    if user_fallback is None or pd.isna(user_fallback):
        user_fallback = 3.5

    shrinkage = support_count / (support_count + shrinkage_k)
    predicted = np.where(
        weight_totals > 0,
        shrinkage * raw_predicted + (1.0 - shrinkage) * user_fallback,
        0.0,
    )

    target_ratings = user_rating_matrix[idx]
    candidate_mask = (target_ratings == 0) & (weight_totals > 0)
    candidate_positions = np.where(candidate_mask)[0]
    if len(candidate_positions) == 0:
        return []

    order = candidate_positions[np.argsort(predicted[candidate_positions])[::-1]]

    result = []
    for p in order:
        tmdb_id = movieid_to_tmdbid.get(movie_columns[p])
        if tmdb_id is None:
            continue  # no bridge available for this movie — skip rather than mis-key it
        result.append((tmdb_id, float(predicted[p])))
        if len(result) >= top_n:
            break
    return result


# -----------------------------------------------------------------------------
# 6. GRADUATED CONFIDENCE (cold -> warm transition, not a hard 0/0.5 switch)
# -----------------------------------------------------------------------------
def calculate_graduated_alpha(num_ratings, alpha_max=0.85, lambda_decay=0.3):
    """alpha(N) = alpha_max * (1 - e^(-lambda * N)), clipped to [0, alpha_max].
    N=0 -> alpha=0 (pure content). Alpha rises smoothly as ratings accumulate,
    approaching alpha_max but never fully trusting a thin rating history."""
    if num_ratings <= 0:
        return 0.0
    return float(np.clip(alpha_max * (1.0 - np.exp(-lambda_decay * num_ratings)), 0.0, alpha_max))


# -----------------------------------------------------------------------------
# 7. HYBRID ENGINE
# -----------------------------------------------------------------------------
def hybrid_recommend(movie_title, user_id, top_n,
                      vectors, all_titles, title_to_pos, pos_to_id, id_to_title,
                      user_rating_matrix, movie_columns, user_index, movieid_to_tmdbid, nbrs,
                      user_rating_counts, user_means, user_stds, popularity_table):

    seed_id, content_recs = (None, [])
    if movie_title:
        seed_id, content_recs = recommend_content(
            movie_title, vectors, all_titles, title_to_pos, pos_to_id, top_n=top_n * 3
        )

    is_known_user = user_id is not None and user_id in user_index

    # --- Regime A: fully cold (no usable movie AND no known user) ----------
    if seed_id is None and not is_known_user:
        print("[INFO] No usable movie title or known user id — using popularity fallback.")
        top_pop = popularity_table.head(top_n)
        return [
            (id_to_title.get(mid, f"id {mid}"), round(float(wr), 1))
            for mid, wr in zip(top_pop['id'], top_pop['weighted_rating'])
        ]

    # --- Regime B / C: graduated alpha based on how much history exists ----
    num_ratings = user_rating_counts.get(user_id, 0) if is_known_user else 0
    alpha = calculate_graduated_alpha(num_ratings)

    if is_known_user:
        print(f"[INFO] User {user_id}: {num_ratings} ratings on record -> alpha = {alpha:.2f}")
    else:
        print(f"[INFO] User unknown/new -> alpha = 0.00 (pure content, seeded from '{movie_title}')")

    collab_recs = (
        recommend_user_based(user_id, user_rating_matrix, movie_columns, user_index,
                              movieid_to_tmdbid, nbrs, user_means=user_means, top_n=top_n * 3)
        if is_known_user else []
    )

    # --- Pure CF pass-through -----------------------------------------------
    # No movie was given (or the title wasn't found), so the content engine
    # contributed nothing — content_recs is empty. In that case hybrid mode
    # should just BE collaborative filtering: surface CF's own predicted
    # rating directly instead of re-deriving a fresh calibrated star through
    # the alpha-blend formula below (which used to run even with alpha's
    # only input being CF, producing a different-looking number for the
    # exact same ranking). is_known_user is guaranteed True here — the
    # fully-cold case (no movie AND no known user) already returned via
    # Regime A above.
    if not content_recs:
        if not collab_recs:
            print("[INFO] No CF candidates for this user — falling back to popularity.")
            top_pop = popularity_table.head(top_n)
            return [
                (id_to_title.get(mid, f"id {mid}"), round(float(wr), 1))
                for mid, wr in zip(top_pop['id'], top_pop['weighted_rating'])
            ]
        ranked = sorted(collab_recs, key=lambda x: x[1], reverse=True)[:top_n]
        return [
            (id_to_title.get(mid, f"id {mid}"), round(float(max(1.0, min(5.0, rating))), 1))
            for mid, rating in ranked
        ]

    c_dict = dict(content_recs)
    raw_collab = dict(collab_recs)
    # Normalize predicted ratings (roughly 1-5 scale) into a 0-1 relevance score
    collab_dict = {mid: max(0.0, min(1.0, (s - 1.0) / 4.0)) for mid, s in raw_collab.items()}

    all_ids = set(c_dict) | set(collab_dict)
    if not all_ids:
        print("[INFO] No candidates from either engine — falling back to popularity.")
        top_pop = popularity_table.head(top_n)
        return [
            (id_to_title.get(mid, f"id {mid}"), round(float(wr), 1))
            for mid, wr in zip(top_pop['id'], top_pop['weighted_rating'])
        ]

    max_c = max(c_dict.values()) if c_dict else 1.0
    max_cf = max(collab_dict.values()) if collab_dict else 1.0

    u_mean = user_means.get(user_id, 3.5) if is_known_user else 3.5
    u_std = user_stds.get(user_id, 1.0) if is_known_user else 1.0
    if not u_std or pd.isna(u_std):
        u_std = 1.0

    # ONE scoring formula applied to the whole list, chosen once per call
    # (not per item). Using a different formula per item put content- and
    # collaborative-sourced candidates on two incomparable scales, so
    # content items always outranked collaborative ones regardless of
    # alpha. hybrid_score already encodes item-level cold start correctly
    # (item_alpha=0 for items with no collaborative signal), so a single
    # consistent formula is enough — no per-item branching needed.
    use_calibrated_scale = is_known_user and num_ratings > 0

    merged = []
    for mid in all_ids:
        norm_c = (c_dict.get(mid, 0.0) / max_c) if max_c > 0 else 0.0
        norm_cf = (collab_dict.get(mid, 0.0) / max_cf) if max_cf > 0 else 0.0

        # Item-level cold start: if THIS movie has no collaborative signal
        # at all, score it purely on content regardless of the user's alpha.
        has_collab_signal = mid in collab_dict
        item_alpha = alpha if has_collab_signal else 0.0

        hybrid_score = item_alpha * norm_cf + (1.0 - item_alpha) * norm_c

        if use_calibrated_scale:
            stars = u_mean + (hybrid_score - 0.5) * 2.0 * u_std
        else:
            stars = 3.5 + hybrid_score * 1.4

        stars = max(1.0, min(5.0, stars))
        merged.append((id_to_title.get(mid, f"id {mid}"), stars))

    # Sort on the raw float score, not the rounded display value — sorting
    # on rounded stars creates spurious ties (e.g. 3.36 vs 3.39 both -> 3.4)
    # whose break order depends on arbitrary set-iteration order, so the
    # same underlying scores can print in a different order across runs.
    merged.sort(key=lambda x: x[1], reverse=True)
    return [(title, round(stars, 1)) for title, stars in merged[:top_n]]


# -----------------------------------------------------------------------------
# 8. INTERACTIVE TERMINAL APP
# -----------------------------------------------------------------------------
def run_interactive():
    print("Building content feature space & TF-IDF vectors...")
    data, vectors, all_titles, title_to_pos, pos_to_id, id_to_title = build_content_based()

    print("Building popularity fallback table...")
    popularity_table = build_popularity_table()

    print("Building collaborative matrix & pre-fitting NearestNeighbors model...")
    (user_rating_matrix, movie_columns, user_index, movieid_to_tmdbid,
     nbrs, user_rating_counts, user_means, user_stds) = build_collaborative(data)

    print("\n=======================================================")
    print("HYBRID MOVIE RECOMMENDATION SYSTEM")
    print("Enter a movie title, a user id, both, or neither.")
    print("(type 'quit' to exit)")
    print("=======================================================")

    while True:
        movie = input("\nMovie title (or 'quit'): ").strip()
        if movie.lower() in ('quit', 'exit'):
            break

        raw_id = input("User ID (or press Enter to skip): ").strip()
        user_id = int(raw_id) if raw_id.isdigit() else None

        results = hybrid_recommend(
            movie_title=movie if movie else None,
            user_id=user_id,
            top_n=5,
            vectors=vectors, all_titles=all_titles, title_to_pos=title_to_pos,
            pos_to_id=pos_to_id, id_to_title=id_to_title,
            user_rating_matrix=user_rating_matrix, movie_columns=movie_columns,
            user_index=user_index, movieid_to_tmdbid=movieid_to_tmdbid, nbrs=nbrs,
            user_rating_counts=user_rating_counts, user_means=user_means,
            user_stds=user_stds, popularity_table=popularity_table,
        )

        print("\nRecommendations:")
        if not results:
            print(" (none found)")
        for title, stars in results:
            print(" -", title, f"(Est. \u2605 {stars})")


if __name__ == "__main__":
    run_interactive()
